### ISSUE TITLE
DPU loading by default on product pages

### ISSUE THREAD

**Issue by torvista** [Zen4All-nl/Zen-Cart-Dynamic-Price-Updater#6]
Hi,
correct me if I am wrong, but DPU is only used for a product with attributes....so why not test for attributes first, prior to testing for these exceptions, and so avoid loading it unnecessarily?

>   $load = true; // if any of the PHP conditions fail this will be set to false and DPU won't be fired up
  $pid = (!empty($_GET['products_id']) ? (int)$_GET['products_id'] : 0);
  if (0 == $pid) {
    $load = false;
  } elseif (zen_get_products_price_is_call($pid) || zen_get_products_price_is_free($pid) || STORE_STATUS > 0) {
    $load = false;
  }
  $pidp = zen_get_products_display_price($pid);
  if (empty($pidp)) {
    $load = false;
  }

**Comment by mc12345678** [comment]
Something of a cross post (as not posted at the forked repository that has been being updated), but the code also addresses/adjusts for quantities of product to be added to the cart with consideration of product quantity already in the cart.  This means that it also accounts for quantity discounts and other calculations to be performed in the shopping cart.  So, no, not just attributes.

Further, these tests are in general in order of conditions required to support even performing any evaluation:
1. Is a product even identified? This is mostly a URL sanitization to ensure a number is identified.  
2. Is there a known reason to not account for any adjustments (ie. if a call needs to be made about the product then no matter how many are present a call likely needs to be made so don't try to do any screen manipulations, same for ordering 2, 3, 4, etc... count of a free product is still free and well, if the store's status is basically set to not display prices then no reason to try to "adjust" for them.)
3. If it has passed that, then see if there is a price to display of some sort. If there is no price information to display (lowest price, current price, to be determined, or something, then likely as far as a default ZC store, any changes to the page are not going to change the display price.  If the `zen_get_products_display_price` function results have been modified to provide an "empty" condition, then don't load the price change code.  This last one is based on the concept that no matter the configuration of the product, the expectation is that a price or text about the price will be displayed for a product that has some price associated with it (I have found a case where this occurs, but it does not seem to be by design but instead by not building in associated handling yet).  Could this third test be bypassed if `$load` is already false?  Perhaps, but I didn't see a reason to make it dependent on the pass/fail of the previous tests especially if the function has been designed to provide some specific desired response upon which one would prefer to act.  One could consider there to be a reason to go ahead and move forward with loading if they so chose based on the response of that function.

Just because I didn't see a need for a default ZC store to absolutely process the `zen_get_products_display_price` result, based on the description of the function and its intended purpose, I didn't see how normal operation would be hurt by allowing it to process even if a previous condition identified `$load` to be false. Further if that one line causes an excess amount of processing on a site, then sure it could be skipped if desired, though I might question the amount of additional effort that is incurred to determine the display price of a product that is currently being displayed...

**Comment by torvista** [comment]
https://www.youtube.com/watch?v=UOHMg7IkzHU
